-- ============================================================
-- SCHÉMA OFFICIEL DE LA BASE DE DONNÉES GBLRECOVER
-- ============================================================

-- 1. TABLE : CENTRE
CREATE TABLE IF NOT EXISTS CENTRE (
    NOM_CENTRE varchar(128) NOT NULL,
    CONSTRAINT PK_CENTRE PRIMARY KEY (NOM_CENTRE)
);

-- 2. TABLE : AGENCE
CREATE TABLE IF NOT EXISTS AGENCE (
    NOM_CENTRE varchar(128) NOT NULL,
    NOM_AGENCE varchar(128) NULL,
    ID_AGENCE varchar(128) NOT NULL,
    CONSTRAINT PK_AGENCE PRIMARY KEY (ID_AGENCE),
    CONSTRAINT FK_AGENCE_CENTRE FOREIGN KEY (NOM_CENTRE) REFERENCES CENTRE(NOM_CENTRE)
);

-- 3. TABLE : GESTIONNAIRE
CREATE TABLE IF NOT EXISTS GESTIONNAIRE (
    MAT_GESTIONNAIRE varchar(128) NOT NULL,
    NOM_GESTIONNAIRE varchar(128) NOT NULL,
    TEL_GESTIONNAIRE int8 NULL,
    EMAIL_GESTIONNAIRE varchar(128) NULL,
    CONSTRAINT PK_GESTIONNAIRE PRIMARY KEY (MAT_GESTIONNAIRE)
);

-- 4. TABLE : CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
    CODE_CLIENT int8 NOT NULL,
    RAISON_SOCIALE varchar(128) NOT NULL,
    MARCHE char(50) NULL,
    EMAIL varchar(128) NULL,
    TEL int8 NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (CODE_CLIENT)
);

-- 5. TABLE : COMPTE
CREATE TABLE IF NOT EXISTS COMPTE (
    NUM_COMPTE int8 NOT NULL,
    MAT_GESTIONNAIRE varchar(128) NULL,
    ID_AGENCE varchar(128) NOT NULL,
    CODE_CLIENT int8 NOT NULL,
    E_BILL varchar(50) NULL,
    STATUT_FACTURATION varchar(50) NULL,
    IDENTIFICATION varchar(128) NULL,
    BALANCE float4 NOT NULL,
    CONSTRAINT PK_COMPTE PRIMARY KEY (NUM_COMPTE),
    CONSTRAINT FK_COMPTE_GESTIONNAIRE FOREIGN KEY (MAT_GESTIONNAIRE) REFERENCES GESTIONNAIRE(MAT_GESTIONNAIRE),
    CONSTRAINT FK_COMPTE_AGENCE FOREIGN KEY (ID_AGENCE) REFERENCES AGENCE(ID_AGENCE),
    CONSTRAINT FK_COMPTE_CLIENT FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENT(CODE_CLIENT)
);

-- 6. TABLE : SERVICE
CREATE TABLE IF NOT EXISTS SERVICE (
    TYPE_SERVICE varchar(128) NOT NULL,
    LIBELLE_SERVICE varchar(128) NULL,
    CONSTRAINT PK_SERVICE PRIMARY KEY (TYPE_SERVICE)
);

-- 7. TABLE : SOUSCRIRE
CREATE TABLE IF NOT EXISTS SOUSCRIRE (
    TYPE_SERVICE varchar(128) NOT NULL,
    NUM_COMPTE int8 NOT NULL,
    DATE_SOUSCRIPTION date NULL,
    STATUT_SOUSCRIPTION varchar(50) NULL,
    CONSTRAINT PK_SOUSCRIRE PRIMARY KEY (TYPE_SERVICE, NUM_COMPTE),
    CONSTRAINT FK_SOUSCRIRE_SERVICE FOREIGN KEY (TYPE_SERVICE) REFERENCES SERVICE(TYPE_SERVICE),
    CONSTRAINT FK_SOUSCRIRE_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES COMPTE(NUM_COMPTE)
);

-- 8. TABLE : FACTURE
CREATE TABLE IF NOT EXISTS FACTURE (
    ID_FACTURE varchar(128) NOT NULL,
    NUM_COMPTE int8 NOT NULL,
    DATE_EMISSION date NOT NULL,
    MONTANT_FACTURE int8 NULL,
    MONTANT_IMPAYE int8 NULL,
    CONSTRAINT PK_FACTURE PRIMARY KEY (ID_FACTURE),
    CONSTRAINT FK_FACTURE_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES COMPTE(NUM_COMPTE)
);

-- 9. TABLE : PAIEMENT
CREATE TABLE IF NOT EXISTS PAIEMENT (
    ID_PAIEMENT varchar(128) NOT NULL,
    ID_FACTURE varchar(128) NOT NULL,
    DATE_PAIEMENT date NULL,
    MONTANT_PAYE float4 NULL,
    CONSTRAINT PK_PAIEMENT PRIMARY KEY (ID_PAIEMENT),
    CONSTRAINT FK_PAIEMENT_FACTURE FOREIGN KEY (ID_FACTURE) REFERENCES FACTURE(ID_FACTURE)
);

-- ============================================================
-- INDEXES DE PERFORMANCE
-- ============================================================
CREATE INDEX IF NOT EXISTS I_FK_AGENCE_CENTRE ON AGENCE (NOM_CENTRE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_GESTIONNAIRE ON COMPTE (MAT_GESTIONNAIRE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_AGENCE ON COMPTE (ID_AGENCE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_CLIENT ON COMPTE (CODE_CLIENT);
CREATE INDEX IF NOT EXISTS I_FK_SOUSCRIRE_SERVICE ON SOUSCRIRE (TYPE_SERVICE);
CREATE INDEX IF NOT EXISTS I_FK_SOUSCRIRE_COMPTE ON SOUSCRIRE (NUM_COMPTE);
CREATE INDEX IF NOT EXISTS I_FK_FACTURE_COMPTE ON FACTURE (NUM_COMPTE);
CREATE INDEX IF NOT EXISTS I_FK_PAIEMENT_FACTURE ON PAIEMENT (ID_FACTURE);
CREATE INDEX IF NOT EXISTS I_COMPTE_IDENTIFICATION ON COMPTE (IDENTIFICATION);

-- ============================================================
-- INSERTIONS INITIALES DE RÉFÉRENCE
-- ============================================================
INSERT INTO SERVICE (TYPE_SERVICE, LIBELLE_SERVICE) VALUES 
('LS', 'Ligne Spécialisée'),
('Vobb', 'Voice over Broadband'),
('FTTx', 'Fibre Optique'),
('TV', 'Télévision'),
('ADSL', 'Haut Débit ADSL'),
('Mobile', 'Réseau Mobile'),
('Autres', 'Autres Services')
ON CONFLICT (TYPE_SERVICE) DO NOTHING;