-- ============================================================
-- SCHÉMA OFFICIEL DE LA BASE DE DONNÉES GBLRECOVER
-- ============================================================

-- 1. TABLE : CENTRE
CREATE TABLE IF NOT EXISTS CENTRE (
    NOM_CENTRE varchar(128) NOT NULL,
    CONSTRAINT PK_CENTRE PRIMARY KEY (NOM_CENTRE)
);

-- 2. TABLE : AGENCE
CREATE TABLE IF NOT EXISTS AGENCE (
    NOM_CENTRE varchar(128) NOT NULL,
    NOM_AGENCE varchar(128) NULL,
    ID_AGENCE varchar(128) NOT NULL,
    CONSTRAINT PK_AGENCE PRIMARY KEY (ID_AGENCE),
    CONSTRAINT FK_AGENCE_CENTRE FOREIGN KEY (NOM_CENTRE) REFERENCES CENTRE(NOM_CENTRE)
);

-- 3. TABLE : GESTIONNAIRE
CREATE TABLE IF NOT EXISTS GESTIONNAIRE (
    MAT_GESTIONNAIRE varchar(128) NOT NULL,
    NOM_GESTIONNAIRE varchar(128) NOT NULL,
    TEL_GESTIONNAIRE int8 NULL,
    EMAIL_GESTIONNAIRE varchar(128) NULL,
    CONSTRAINT PK_GESTIONNAIRE PRIMARY KEY (MAT_GESTIONNAIRE)
);

-- 4. TABLE : CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
    CODE_CLIENT int8 NOT NULL,
    RAISON_SOCIALE varchar(128) NOT NULL,
    MARCHE char(50) NULL,
    EMAIL varchar(128) NULL,
    TEL int8 NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (CODE_CLIENT)
);

-- 5. TABLE : COMPTE
CREATE TABLE IF NOT EXISTS COMPTE (
    NUM_COMPTE int8 NOT NULL,
    MAT_GESTIONNAIRE varchar(128) NULL,
    ID_AGENCE varchar(128) NOT NULL,
    CODE_CLIENT int8 NOT NULL,
    E_BILL varchar(50) NULL,
    STATUT_FACTURATION varchar(50) NULL,
    IDENTIFICATION varchar(128) NULL,
    BALANCE float4 NOT NULL,
    CONSTRAINT PK_COMPTE PRIMARY KEY (NUM_COMPTE),
    CONSTRAINT FK_COMPTE_GESTIONNAIRE FOREIGN KEY (MAT_GESTIONNAIRE) REFERENCES GESTIONNAIRE(MAT_GESTIONNAIRE),
    CONSTRAINT FK_COMPTE_AGENCE FOREIGN KEY (ID_AGENCE) REFERENCES AGENCE(ID_AGENCE),
    CONSTRAINT FK_COMPTE_CLIENT FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENT(CODE_CLIENT)
);

-- 6. TABLE : SERVICE
CREATE TABLE IF NOT EXISTS SERVICE (
    TYPE_SERVICE varchar(128) NOT NULL,
    LIBELLE_SERVICE varchar(128) NULL,
    CONSTRAINT PK_SERVICE PRIMARY KEY (TYPE_SERVICE)
);

-- 7. TABLE : SOUSCRIRE
CREATE TABLE IF NOT EXISTS SOUSCRIRE (
    TYPE_SERVICE varchar(128) NOT NULL,
    NUM_COMPTE int8 NOT NULL,
    DATE_SOUSCRIPTION date NULL,
    STATUT_SOUSCRIPTION varchar(50) NULL,
    CONSTRAINT PK_SOUSCRIRE PRIMARY KEY (TYPE_SERVICE, NUM_COMPTE),
    CONSTRAINT FK_SOUSCRIRE_SERVICE FOREIGN KEY (TYPE_SERVICE) REFERENCES SERVICE(TYPE_SERVICE),
    CONSTRAINT FK_SOUSCRIRE_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES COMPTE(NUM_COMPTE)
);

-- 8. TABLE : FACTURE
CREATE TABLE IF NOT EXISTS FACTURE (
    ID_FACTURE varchar(128) NOT NULL,
    NUM_COMPTE int8 NOT NULL,
    DATE_EMISSION date NOT NULL,
    MONTANT_FACTURE numeric(14,2) NULL,
    TYPE_FLUX varchar(50) DEFAULT 'FACTURE',
    LIBELLE_PERIODE varchar(128) NULL,
    PAID_AMOUNT numeric(14,2) DEFAULT 0,
    OUTSTANDING_AMOUNT numeric(14,2) DEFAULT 0,
    STATUS varchar(50) DEFAULT 'OPEN',
    CONSTRAINT PK_FACTURE PRIMARY KEY (ID_FACTURE),
    CONSTRAINT FK_FACTURE_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES COMPTE(NUM_COMPTE)
);

-- 9. TABLE : PAIEMENT
CREATE TABLE IF NOT EXISTS PAIEMENT (
    ID_PAIEMENT varchar(128) NOT NULL,
    ID_FACTURE varchar(128) NOT NULL,
    DATE_PAIEMENT date NULL,
    MONTANT_PAYE float4 NULL,
    CONSTRAINT PK_PAIEMENT PRIMARY KEY (ID_PAIEMENT),
    CONSTRAINT FK_PAIEMENT_FACTURE FOREIGN KEY (ID_FACTURE) REFERENCES FACTURE(ID_FACTURE)
);

-- ============================================================
-- INDEXES DE PERFORMANCE
-- ============================================================
CREATE INDEX IF NOT EXISTS I_FK_AGENCE_CENTRE ON AGENCE (NOM_CENTRE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_GESTIONNAIRE ON COMPTE (MAT_GESTIONNAIRE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_AGENCE ON COMPTE (ID_AGENCE);
CREATE INDEX IF NOT EXISTS I_FK_COMPTE_CLIENT ON COMPTE (CODE_CLIENT);
CREATE INDEX IF NOT EXISTS I_FK_SOUSCRIRE_SERVICE ON SOUSCRIRE (TYPE_SERVICE);
CREATE INDEX IF NOT EXISTS I_FK_SOUSCRIRE_COMPTE ON SOUSCRIRE (NUM_COMPTE);
CREATE INDEX IF NOT EXISTS I_FK_FACTURE_COMPTE ON FACTURE (NUM_COMPTE);
CREATE INDEX IF NOT EXISTS I_FK_PAIEMENT_FACTURE ON PAIEMENT (ID_FACTURE);
CREATE INDEX IF NOT EXISTS I_COMPTE_IDENTIFICATION ON COMPTE (IDENTIFICATION);

-- ============================================================
-- NOUVELLES TABLES (USERS, ROLES, PERMISSIONS, AUDIT, IMPORT, RECOUVREMENT)
-- ============================================================

CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(30),
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    LAST_LOGIN TIMESTAMPTZ,
    MUST_CHANGE_PASSWORD BOOLEAN DEFAULT FALSE,
    CREATED_BY UUID REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CODE VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS PERMISSIONS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    RESOURCE VARCHAR(50) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CENTRE_ID VARCHAR(128) REFERENCES CENTRE(NOM_CENTRE) ON UPDATE CASCADE ON DELETE CASCADE,
    AGENCY_ID VARCHAR(128) REFERENCES AGENCE(ID_AGENCE) ON UPDATE CASCADE ON DELETE CASCADE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    CREATED_BY UUID REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PERMISSION_ID UUID NOT NULL REFERENCES PERMISSIONS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE IF NOT EXISTS COLLECTION_ACTIONS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ACCOUNT_ID int8 NOT NULL REFERENCES COMPTE(NUM_COMPTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    CREATED_BY UUID NOT NULL REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    ASSIGNED_TO UUID REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PLANNED',
    DUE_DATE DATE NOT NULL,
    COMPLETED_AT TIMESTAMPTZ,
    COMMENT TEXT,
    RESULT VARCHAR(255),
    PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS PROMISES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    COLLECTION_ACTION_ID UUID NOT NULL REFERENCES COLLECTION_ACTIONS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    ACCOUNT_ID int8 NOT NULL REFERENCES COMPTE(NUM_COMPTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    PROMISED_AMOUNT numeric(14,2) NOT NULL,
    PROMISED_DATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    NOTES TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS AUDIT_EVENTS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    ACTION VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    ENTITY_ID VARCHAR(128) NOT NULL,
    OLD_VALUES JSONB,
    NEW_VALUES JSONB,
    IP_ADDRESS INET,
    USER_AGENT TEXT,
    REQUEST_ID VARCHAR(36),
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS IMPORT_BATCHES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FILENAME VARCHAR(255) NOT NULL,
    FILE_CHECKSUM VARCHAR(64) NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    TOTAL_ROWS INTEGER,
    PROCESSED_ROWS INTEGER DEFAULT 0,
    ACCEPTED_ROWS INTEGER DEFAULT 0,
    REJECTED_ROWS INTEGER DEFAULT 0,
    STARTED_AT TIMESTAMPTZ,
    COMPLETED_AT TIMESTAMPTZ,
    CREATED_BY UUID NOT NULL REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS IMPORT_ERRORS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BATCH_ID UUID NOT NULL REFERENCES IMPORT_BATCHES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    ROW_NUMBER INTEGER NOT NULL,
    COLUMN_NAME VARCHAR(50),
    RAW_VALUE TEXT,
    ERROR_MESSAGE TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for new tables
CREATE INDEX IF NOT EXISTS I_USERS_EMAIL ON USERS (EMAIL);
CREATE INDEX IF NOT EXISTS I_USERS_STATUS ON USERS (STATUS);
CREATE INDEX IF NOT EXISTS I_COLLECTION_ACTIONS_ACCOUNT ON COLLECTION_ACTIONS (ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS I_COLLECTION_ACTIONS_CREATED_BY ON COLLECTION_ACTIONS (CREATED_BY);
CREATE INDEX IF NOT EXISTS I_PROMISES_ACCOUNT ON PROMISES (ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS I_AUDIT_EVENTS_USER ON AUDIT_EVENTS (USER_ID);
CREATE INDEX IF NOT EXISTS I_IMPORT_BATCHES_STATUS ON IMPORT_BATCHES (STATUS);

-- ============================================================
-- INSERTIONS INITIALES DE RÉFÉRENCE
-- ============================================================
INSERT INTO SERVICE (TYPE_SERVICE, LIBELLE_SERVICE) VALUES 
('LS', 'Ligne Spécialisée'),
('Vobb', 'Voice over Broadband'),
('FTTx', 'Fibre Optique'),
('TV', 'Télévision'),
('ADSL', 'Haut Débit ADSL'),
('Mobile', 'Réseau Mobile'),
('Autres', 'Autres Services')
ON CONFLICT (TYPE_SERVICE) DO NOTHING;